### ISSUE TITLE
Swop all checkboxes for toggles

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#78]
I love the toggles @jorgerobles used in settings
![switches](https://cloud.githubusercontent.com/assets/7695323/21173170/1fe27464-c1df-11e6-9321-fc72dda97cfe.PNG)

Any chance we can use them everywhere, for instance the checkboxes in CAM too?
![cam](https://cloud.githubusercontent.com/assets/7695323/21173182/2947462e-c1df-11e6-9ea9-fa77f49f98fc.PNG)

**Comment by tbfleming** [comment]
If they can be shrunk to not waste vertical space

**Comment by jorgerobles** [comment]
only use className="scaleHalf" (not commited yet) and done :P 

![tada](https://cloud.githubusercontent.com/assets/1706080/21185359/a54c99dc-c210-11e6-8af2-509c32a2da94.png)

**Comment by tbfleming** [comment]
@jorgerobles it's not always dispatching the actions.

**Comment by openhardwarecoza** [comment]
Initial state of the toggle is wrong.  (Union is performed, though Union toggle is off.  First click turns on Union (CAM still Unions) and Second click finally works correctly (disabling Union in the app)

**Comment by jorgerobles** [comment]
Fixed!

**Comment by openhardwarecoza** [comment]
Still shows :

![union](https://cloud.githubusercontent.com/assets/7695323/21228204/949ba940-c2e5-11e6-880b-1c7297f7e0b7.PNG)

(Implies the job won't be Unioned)
But clicking generate gcode generates gcode which is Unioned

(IE Union = yes was the default state on cam side?  Maybe the logic of the checkbox is reversed? @tbfleming

**Comment by jorgerobles** [comment]
![union_false](https://cloud.githubusercontent.com/assets/1706080/21228431/07018e94-c2de-11e6-8f71-6eac5a17456c.png)
![union_true](https://cloud.githubusercontent.com/assets/1706080/21228432/07080238-c2de-11e6-913a-a3c54f76b065.png)

**Comment by jorgerobles** [comment]
![may_i_change_it](https://cloud.githubusercontent.com/assets/1706080/21228669/fed3162e-c2de-11e6-8fd5-d1f91c712892.png)

**Comment by openhardwarecoza** [comment]
Yeah man! Now its working perfectly!

Thanks!
